// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWzyfIXNFtCUufJAvMBSzy65hm_o-jIcY',
    appId: '1:718992232719:web:f678cef3bef96347e02e7a',
    messagingSenderId: '718992232719',
    projectId: 'flutter-cubit-firebase',
    authDomain: 'flutter-cubit-firebase.firebaseapp.com',
    storageBucket: 'flutter-cubit-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2v7PDurj0sVx6zRnhjGceDaD9lF4Jn1M',
    appId: '1:718992232719:android:835d85789b549bdbe02e7a',
    messagingSenderId: '718992232719',
    projectId: 'flutter-cubit-firebase',
    storageBucket: 'flutter-cubit-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3-daNW6GkvGJqmWbSCx0RHhzFxogAtz0',
    appId: '1:718992232719:ios:8d5784dda784cb46e02e7a',
    messagingSenderId: '718992232719',
    projectId: 'flutter-cubit-firebase',
    storageBucket: 'flutter-cubit-firebase.appspot.com',
    iosBundleId: 'com.example.flutterCubitFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3-daNW6GkvGJqmWbSCx0RHhzFxogAtz0',
    appId: '1:718992232719:ios:8d5784dda784cb46e02e7a',
    messagingSenderId: '718992232719',
    projectId: 'flutter-cubit-firebase',
    storageBucket: 'flutter-cubit-firebase.appspot.com',
    iosBundleId: 'com.example.flutterCubitFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWzyfIXNFtCUufJAvMBSzy65hm_o-jIcY',
    appId: '1:718992232719:web:3c70c1bb68ee8f20e02e7a',
    messagingSenderId: '718992232719',
    projectId: 'flutter-cubit-firebase',
    authDomain: 'flutter-cubit-firebase.firebaseapp.com',
    storageBucket: 'flutter-cubit-firebase.appspot.com',
  );
}
